# Task 1 – Linear Algebra Implementation 

In [1]:
import numpy as np
vector_a = np.array([2, 4, 6])
vector_b = np.array([1, 3, 5])

matrix_a = np.array([
    [2, 1, 3],
    [1, 0, 2],
    [4, 1, 1]
])

matrix_b = np.array([
    [1, 2, 0],
    [3, 1, 4],
    [2, 5, 1]
])


vector_addition = vector_a + vector_b
print("Vector Addition:", vector_addition)

vector_subtraction = vector_a - vector_b
print("Vector Subtraction:", vector_subtraction)

dot_product = np.dot(vector_a, vector_b)
print("Dot Product:", dot_product)

matrix_addition = matrix_a + matrix_b
print("\nMatrix Addition:")
print(matrix_addition)

matrix_multiplication = np.dot(matrix_a, matrix_b)
print("\nMatrix Multiplication:")
print(matrix_multiplication)

determinant = np.linalg.det(matrix_a)
print("\nDeterminant of Matrix A:", determinant)

if determinant != 0:
    inverse = np.linalg.inv(matrix_a)
    print("\nInverse of Matrix A:")
    print(inverse)
else:
    print("\nMatrix A does not have an inverse.")
eigenvalues, eigenvectors = np.linalg.eig(matrix_a)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Vector Addition: [ 3  7 11]
Vector Subtraction: [1 1 1]
Dot Product: 44

Matrix Addition:
[[3 3 3]
 [4 1 6]
 [6 6 2]]

Matrix Multiplication:
[[11 20  7]
 [ 5 12  2]
 [ 9 14  5]]

Determinant of Matrix A: 6.0

Inverse of Matrix A:
[[-0.33333333  0.33333333  0.33333333]
 [ 1.16666667 -1.66666667 -0.16666667]
 [ 0.16666667  0.33333333 -0.16666667]]

Eigenvalues:
[ 5.54138127 -2.         -0.54138127]

Eigenvectors:
[[-0.66037269 -0.42163702  0.17485589]
 [-0.3575134  -0.52704628 -0.96894315]
 [-0.66037269  0.73786479  0.17485589]]


# Task 2 – Probability Concepts 

In [6]:
import numpy as np
from scipy.stats import binom, norm, uniform
sales_success = [0.65, 0.35]

print("Probability of Successful Sales:", sales_success[0])
print("Probability of Unsuccessful Sales:", sales_success[1])

customer_segments = ["Premium", "Regular"]

segment_purchase_probability = {
    "Premium": 0.80,
    "Regular": 0.50
}

print("\nConditional Probability:")
print("P(Purchase | Premium) =", segment_purchase_probability["Premium"])
print("P(Purchase | Regular) =", segment_purchase_probability["Regular"])

P_A = 0.40
P_B = 0.62
P_B_given_A = 0.80

P_A_given_B = (P_B_given_A * P_A) / P_B

print("\nBayes' Theorem:")
print("Updated Probability P(Premium | Purchase) =", P_A_given_B)

n_trials = 20
success_prob = 0.65

binomial_distribution = binom.pmf(
    np.arange(n_trials + 1),
    n_trials,
    success_prob
)

print("\nBinomial Distribution:")
print(binomial_distribution)
normal_mean = 50
normal_std = 10

normal_distribution = norm.rvs(
    loc=normal_mean,
    scale=normal_std,
    size=100
)

print("\nNormal Distribution:")
print(normal_distribution)

uniform_low = 0
uniform_high = 1

uniform_distribution = uniform.rvs(
    loc=uniform_low,
    scale=uniform_high - uniform_low,
    size=100
)
print("\nUniform Distribution:")
print(uniform_distribution)

Probability of Successful Sales: 0.65
Probability of Unsuccessful Sales: 0.35

Conditional Probability:
P(Purchase | Premium) = 0.8
P(Purchase | Regular) = 0.5

Bayes' Theorem:
Updated Probability P(Premium | Purchase) = 0.5161290322580646

Binomial Distribution:
[7.60958350e-10 2.82641673e-08 4.98660666e-07 5.55650456e-06
 4.38566967e-05 2.60634083e-04 1.21008682e-03 4.49460817e-03
 1.35640854e-02 3.35872590e-02 6.86139720e-02 1.15841771e-01
 1.61351038e-01 1.84401186e-01 1.71229673e-01 1.27199186e-01
 7.38209560e-02 3.22578967e-02 9.98458708e-03 1.95187417e-03
 1.81245458e-04]

Normal Distribution:
[46.3450137  45.79657281 54.57534338 46.83107522 54.63368097 44.39306945
 47.96659941 46.96442576 57.84885906 50.15310733 42.51240824 55.02788611
 56.29746751 34.0275078  54.44060187 58.41565428 48.90123589 38.98908482
 33.48161785 39.16183445 50.39065994 50.96900815 47.2783397  56.96411615
 67.97474918 49.86088478 52.59072682 34.89323757 38.28356893 68.39567272
 63.75619736 40.36216953 50

# Descriptive Statistics

In [7]:
import numpy as np
import pandas as pd
import statistics

sales_data = [120, 135, 150, 145, 160, 155, 170, 165, 180, 175,
              190, 200, 210, 195, 185, 175, 165, 155, 145, 135]

sales = np.array(sales_data)
# 1. Mean
mean = np.mean(sales)
# 2. Median
median = np.median(sales)
# 3. Mode
mode = statistics.multimode(sales_data)
# 4. Range
data_range = np.max(sales) - np.min(sales)
# 5. Variance
variance = np.var(sales)
# 6. Standard Deviation
standard_deviation = np.std(sales)
# 7. Skewness and Kurtosis using Pandas
df = pd.DataFrame({"Sales": sales_data})

skewness = df["Sales"].skew()
kurtosis = df["Sales"].kurt()

print("Descriptive Statistics")
print("----------------------")
print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)
print("Range:", data_range)
print("Variance:", variance)
print("Standard Deviation:", standard_deviation)
print("Skewness:", skewness)
print("Kurtosis:", kurtosis)

print("\nInterpretation:")

if abs(skewness) < 0.5:
    print("The dataset is approximately symmetric.")
elif skewness > 0:
    print("The dataset is positively skewed.")
else:
    print("The dataset is negatively skewed.")

Descriptive Statistics
----------------------
Mean: 165.5
Median: 165.0
Mode: [135, 145, 155, 165, 175]
Range: 90
Variance: 534.75
Standard Deviation: 23.124662159694356
Skewness: 0.03264455519886574
Kurtosis: -0.5493161347714888

Interpretation:
The dataset is approximately symmetric.
